import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "sonner";
import Footer from "../components/Footer"; // ✅ Footer Imported

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Varvadhu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* 🔹 Top Navbar */}
        <Navbar />

        {/* 🔹 Global Toast Notifications */}
        <Toaster position="top-center" richColors />

        {/* 🔹 Page Content */}
        {children}

        {/* 🔹 Footer Added at the Bottom */}
        <Footer />

      </body>
    </html>
  );
}
